[package]
name = "example"
description = "A simple HTTP handler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
spin-sdk = { workspace = true }