[package]
name = "http-auth-middleware"
description = "An HTTP authentication middleware component."
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
http = "0.2"
# spin-sdk = { git = "https://github.com/fermyon/spin", branch = "main" }
spin-sdk = { path = "../spin/sdk/rust" }
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "3518b5e2f08e4028b7f0cf0ed386e03423a3cd1b" }
cookie = "0.18"

[workspace]

[package.metadata.component]
package = "middleware:http-auth"

[package.metadata.component.target.dependencies]
"wasi:http" = { path = "wit/deps/http" }
"wasi:io" = { path = "wit/deps/io" }
