[workspace]
members = [
    "github-oauth",
    "example-app",
]

[workspace.dependencies]
anyhow = "1"
http = "1.0.0"
spin-sdk = "3.0.1"
spin-executor = "3.0.1"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true