spin_manifest_version = 2

[application]
name = "github-oauth2-example"
version = "0.1.0"
description = "A simple HTTP handler"

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = "target/wasm32-wasi/release/github_oauth.wasm"
allowed_outbound_hosts = ["https://github.com", "https://api.github.com"]
[component.frontend.build]
command = "./build.sh"
[component.frontend.dependencies]
"wasi:http/incoming-handler@0.2.0" = { path = "target/wasm32-wasi/release/example.wasm" }
