spin_manifest_version = 2

[application]
name = "github-oauth2-example"
version = "0.1.0"
description = "A simple HTTP handler"

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = "p3/authed_app.wasm"  # for P3 we have to post-process compose in build.sh
allowed_outbound_hosts = ["https://github.com", "https://api.github.com"]
[component.frontend.build]
command = "./build.sh"
# Unused because for now we have to precompose in build.sh
# [component.frontend.dependencies]
# "wasi:http/incoming-handler@0.2.0" = { path = "target/wasm32-wasip1/release/example.wasm" }
