package double:http;

interface chain-http {
    use wasi:http/types@0.3.0-rc-2025-09-16.{request, response, error-code};

  handle: async func(
    request: request,
  ) -> result<response, error-code>;
}

world middleware {
  import chain-http;
}
